version: '3'
services:
  pg-admin:
    container_name: pg-admin
    image: dpage/pgadmin4
    user: root:root
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=t.hamoudi@josa.ngo
      - PGADMIN_DEFAULT_PASSWORD=admin
    network_mode: host